"""Generate Comments_Response_C2_C3.docx"""
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

doc = Document()

# ---- Page setup ----
for section in doc.sections:
    section.top_margin = Cm(2.54)
    section.bottom_margin = Cm(2.54)
    section.left_margin = Cm(3.18)
    section.right_margin = Cm(3.18)

style = doc.styles['Normal']
font = style.font
font.name = 'Times New Roman'
font.size = Pt(12)
style.paragraph_format.line_spacing = 1.5

# ---- Title ----
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = title.add_run('Response to Reviewer Comments:\nComment 2 (\u03bb_\u03a9 Robustness) & Comment 3 (High-Dimensional Feasibility)')
run.bold = True
run.font.size = Pt(16)
run.font.color.rgb = RGBColor(0, 0, 0)

doc.add_paragraph()
meta = doc.add_paragraph()
meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
meta.add_run('Realized Weight Forecasting with Network-Regularized VARX\n').font.size = Pt(11)
meta.add_run('Generated: 2026-07-18 | Script: generate_comments_response.py').font.size = Pt(10)

doc.add_page_break()

# ===================================================================
# Helper functions
# ===================================================================
def add_heading(text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0, 51, 102)
    return h

def add_body(text):
    p = doc.add_paragraph(text)
    p.paragraph_format.first_line_indent = Cm(0.75)
    return p

def add_quote(text):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Cm(1.5)
    p.paragraph_format.right_indent = Cm(1.5)
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(10.5)
    run.font.color.rgb = RGBColor(80, 80, 80)
    return p

def add_table(headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Light Grid Accent 1'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    # Header
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = h
        for p in cell.paragraphs:
            for r in p.runs:
                r.bold = True
                r.font.size = Pt(10)
    # Data
    for ri, row in enumerate(rows):
        for ci, val in enumerate(row):
            cell = table.rows[ri + 1].cells[ci]
            cell.text = str(val)
            for p in cell.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(10)
    doc.add_paragraph()
    return table

# ===================================================================
# COMMENT 2
# ===================================================================
add_heading('Comment 2: First-Stage Regularization Robustness (\u03bb_\u03a9)', level=1)

add_heading('2.1 Reviewer Comment', level=2)
add_quote(
    '\u201cThe realized GMVP weights used as the forecasting target are generated from a '
    'graphical-lasso estimator. Consequently, the forecasting target depends on the tuning '
    'parameter \u03bb_\u03a9. The reported forecasting performance may therefore depend on the '
    'first-stage regularization choice rather than on the true latent GMVP dynamics.\u201d'
)

add_heading('2.2 Our Response', level=2)
add_body(
    'The core mechanism driving M4 (Network VARX) over M3a (Sparse VARX without network penalty) '
    'is the relative differentiation of the L1 penalty: connected asset pairs receive \u03bb\u2081, '
    'whereas unconnected pairs receive a larger penalty \u03bb\u2082 = \u03bb\u2081 + \u03bb_net. '
    'This differentiation relies on the adjacency matrix derived from the GLasso precision matrix, '
    'which in turn depends on \u03bb_\u03a9. To assess robustness, we examine whether the network '
    'structure remains discriminative across a wide range of \u03bb_\u03a9 values.'
)

add_heading('2.3 Data Source and Script', level=2)
add_body(
    'Data generated by: [Script] GLasso/code/weights_minimal.py\n'
    'This is a lightweight, single-process GLasso implementation with an adaptive Ridge fallback '
    'chain [5\u00d710\u207b\u2074, 10\u207b\u00b3, 5\u00d710\u207b\u00b3, 10\u207b\u00b2] to ensure '
    'convergence. We randomly sample 20 trading days from the full 2,436-day dataset and compute '
    'the adjacency matrix at three \u03bb_\u03a9 values spanning an order of magnitude.'
)

add_heading('2.4 Results', level=2)
add_table(
    ['\u03bb_\u03a9', 'Success Rate', 'Mean Network Density', 'Computation Time'],
    [
        ['1 \u00d7 10\u207b\u2076', '20/20', '80.8%', '366s'],
        ['3 \u00d7 10\u207b\u2076 (chosen)', '20/20', '56.8%', '292s'],
        ['1 \u00d7 10\u207b\u2075', '20/20', '33.9%', '121s'],
    ]
)
add_body(
    'Across \u03bb_\u03a9 \u2208 {10\u207b\u2076, 3\u00d710\u207b\u2076, 10\u207b\u2075}, the raw adjacency '
    'density ranges from 33.9% to 80.8%. The network never collapses to a complete graph (density '
    '= 100%) nor degenerates to an empty graph (density = 0%). With our chosen threshold \u03c4 = 0.7 '
    'applied to the 20-day rolling average \u0100, the effective penalty mask remains sparse and '
    'discriminative across all \u03bb_\u03a9 values.'
)

add_heading('2.5 Conclusion', level=2)
add_body(
    'The relative differentiation of connected versus unconnected penalty terms\u2014the core mechanism '
    'underlying M4\u2019s superior forecasting performance\u2014is robust to the choice of first-stage '
    'regularization \u03bb_\u03a9. The network structure remains informative across an order-of-magnitude '
    'range, supporting the validity of our reported results.'
)

# ===================================================================
# COMMENT 3
# ===================================================================
doc.add_page_break()
add_heading('Comment 3: High-Dimensional Feasibility', level=1)

add_heading('3.1 Reviewer Comment', level=2)
add_quote(
    '\u201cThe VARX model is extremely high-dimensional. With K assets and p lags, the autoregressive '
    'component alone contains pK\u00b2 coefficients. It is unclear whether the available time-series '
    'sample is sufficient to estimate this model reliably, even with Lasso-type penalties.\u201d'
)

add_heading('3.2 Our Response', level=2)
add_body(
    'The VARX model is estimated equation-by-equation via independent Lasso regressions. Each of '
    'the K = 392 asset equations has its own training sample of T = 1,690 observations and '
    'p = 1,185 features (P_LAGS \u00d7 K = 1,176 lagged weights + 9 exogenous variables). '
    'This is not a joint estimation of the full 464,520-parameter system; rather, it is 392 '
    'separate high-dimensional Lasso problems, each with T \u226b effective degrees of freedom.'
)

add_heading('3.3 Data Source and Script', level=2)
add_body(
    'Data generated by: [Script] VARX/grid_search.py '
    '(hierarchical ablation parameter search, 3-fold expanding validation window)\n'
    'Output: [File] VARX/final_params.json\n\n'
    'The grid search systematically explores penalty parameters (\u03bb\u2081, \u03bb\u2083, \u03bb_net, '
    '\u03c4, \u03bb_s) for models M2 through M5. P0 verified that M2\u2019s \u03bb\u2081 = 5\u00d710\u207b\u2074 '
    'is not a boundary artifact; P1 identified M3a\u2019s independent optimal \u03bb\u2081 = 4.5\u00d710\u207b\u2074 '
    '(rather than inheriting M3\u2019s 3\u00d710\u207b\u2074); P2 confirmed \u03bb\u2083 = 5\u00d710\u207b\u2074 as '
    'optimal for the full M5+DFL pipeline. All results are averaged over 3 validation folds.'
)

add_heading('3.4 Results', level=2)
add_body('Effective sparsity of the fitted M4 (Network VARX) model:')
add_table(
    ['Metric', 'Value'],
    [
        ['Total coefficients', 'K \u00d7 (P\u00b7K + N_exog) = 392 \u00d7 1,185 = 464,520'],
        ['Non-zero coefficients (mean_n_alive)', '5,344'],
        ['Overall sparsity', '98.85%'],
        ['Non-zero per equation (average)', '13.6'],
        ['Training sample size T', '1,690'],
        ['Effective ratio T / p_eff', '\u2248 124'],
    ]
)

add_body('Benchmark models for comparison:')
add_table(
    ['Model', 'Sparsity', 'Non-zero / Equation', 'T / p_eff'],
    [
        ['M2 (Sparse VAR)', '98.92%', '\u2248 12.7', '\u2248 133'],
        ['M3 (Sparse VARX)', '97.03%', '\u2248 35.2', '\u2248 48'],
        ['M4 (Network VARX)', '98.85%', '\u2248 13.6', '\u2248 124'],
    ]
)

add_heading('3.5 Conclusion', level=2)
add_body(
    'With an effective sample-to-parameter ratio of approximately 124:1 per equation, the Lasso '
    'estimator operates well within the regime where oracle inequalities and variable-selection '
    'consistency results apply (e.g., B\u00fchlmann & van de Geer, 2011, Ch. 6\u20137). '
    'Importantly, simpler alternatives\u2014unregularized VAR (M1, T/p_eff \u226a 1) and lag-only '
    'Sparse VAR (M2)\u2014serve as benchmarks and are uniformly outperformed by the proposed model '
    'in out-of-sample prediction accuracy (Table 2) and portfolio performance (Table 3). '
    'The high-dimensional setting is therefore not a limitation but a feature: the Lasso-based '
    'approach leverages sparsity to identify a parsimonious yet predictive model from a rich '
    'set of candidate predictors.'
)

# ---- Footer ----
doc.add_paragraph()
footer_para = doc.add_paragraph()
footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = footer_para.add_run('\u2014 End of Response \u2014')
run.font.size = Pt(9)
run.font.color.rgb = RGBColor(128, 128, 128)

# ---- Save ----
output_path = 'D:/HuaweiMoveData/Users/27438/Desktop/大创/Comments_Response_C2_C3.docx'
doc.save(output_path)
print(f'Saved: {output_path}')
